<a href="https://colab.research.google.com/github/cher-16/maths-python-notebooks/blob/main/Week_2_Colab_NumPy_SymPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 Week 2: Math with Python - NumPy & SymPy

Welcome to Week 2! This week you'll learn how to use:

- **NumPy** for numerical and linear algebra computations
- **SymPy** for symbolic algebra, solving equations, and calculus

By the end of this notebook, you’ll be able to:
- Perform vector and matrix operations using NumPy
- Solve equations and compute derivatives using SymPy


## 🔢 NumPy Basics

Let's start with arrays and basic operations.


In [ ]:
import numpy as np

# Create vectors
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

# Vector addition
print("v + w =", v + w)

# Dot product
print("Dot product:", np.dot(v, w))

# Create a matrix
A = np.array([[1, 2], [3, 4]])
print("Matrix A:\n", A)

# Transpose and inverse
print("Transpose\n:", A.T)
print("Inverse:\n", np.linalg.inv(A))


v + w = [5 7 9]
Dot product: 32
Matrix A:
 [[1 2]
 [3 4]]
Transpose
: [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## 🌟 NumPy Challenge

1. Create a 3x3 matrix `B` with values from 1 to 9.
2. Compute its determinant.
3. Compute its eigenvalues and eigenvectors.


In [16]:
# Your NumPy challenge code here
import numpy as np
from numpy import linalg as LA

# Define matrix B
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix B:\n", B)

# Compute the determinant of B
det_B = LA.det(B)
print("Determinant of B:\n", det_B)

# Compute the eigenvalues and eigenvectors of B
eigvals, eigvecs = LA.eig(B)
print("\nEigenvalues of B:\n", eigvals)
print("\nEigenvectors of B:\n", eigvecs)


Matrix B:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of B:
 0.0

Eigenvalues of B:
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]

Eigenvectors of B:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## 🧠 SymPy Basics

Now let’s explore symbolic math using SymPy.


In [ ]:
import sympy as sp

# Define a symbol
x = sp.Symbol('x')

# Define a function
f = x**3 + 2*x**2 + x + 1

# Derivative
f_prime = sp.diff(f, x)
print("f'(x) =", f_prime)

# Integral
f_int = sp.integrate(f, x)
print("∫f(x) dx =", f_int)

# Solve an equation
solution = sp.solve(x**2 - 2, x)
print("Solutions to x^2 - 2 = 0:", solution)


## 🌟 SymPy Challenge

1. Define a new function `g(x) = sin(x) * e^x`.
2. Compute its derivative.
3. Compute the definite integral from 0 to π.

Use `sp.sin(x)` and `sp.exp(x)`.


In [17]:
# Your SymPy challenge code here
import sympy as sp

# Define a symbol
x = sp.Symbol('x')

# Define a function
g = sp.sin(x) * sp.exp(x)

# Derivative
g_prime = sp.diff(g, x)
print("g'(x) =", g_prime)

# Integral (Definite)
g_int = sp.integrate(g, (x, 0, sp.pi))
print("∫g(x) dx =", g_int)

g'(x) = exp(x)*sin(x) + exp(x)*cos(x)
∫g(x) dx = 1/2 + exp(pi)/2


## 🧪 Quick Quiz

1. What's the difference between `np.dot()` and `np.multiply()`?
2. What does `sp.solve()` do?
3. What does `np.linalg.inv()` return?


Your answers here:

1. np.dot() gives dot product of two arrays, and np.multiply() performs element-wise multiplication two arrays.

2. sp.solve() solves a system of linear equations represented by ax = b, where a is a square matrix and b is a vector or matrix.

3. np.linalg.inv() returns inverse matrix of the given square matrix.
